services:

    postgres:
      image: 'postgres:17.6-alpine'
      container_name: 'postgres'
      environment:
        POSTGRES_DB: 'orka'
        POSTGRES_USER: 'orka'
        POSTGRES_PASSWORD: 'ChangeMe#2025'
      volumes:
        - 'postgres_data:/var/lib/postgresql/data'
      networks:
        - 'local'
      ports:
        - '5432:5432/tcp'
      deploy:
        resources:
          reservations:
            memory: '256M'
          limits:
            memory: '256M'
      healthcheck:
        test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
        interval: 30s
        timeout: 10s
        retries: 10

volumes:
  postgres_data: {}
